# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('initials', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('lattes_link', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=25)),
                ('scholarship_type', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Institution')),
            ],
            options={
                'ordering': ('scholarship', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('initials', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScholarshipFounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.ScholarshipFounder'),
        ),
        migrations.AddField(
            model_name='member',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Scholarship'),
        ),
    ]
