# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='institution',
            name='department',
        ),
        migrations.AlterField(
            model_name='institution',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Degree'),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Degree'),
        ),
        migrations.AddField(
            model_name='institutiondepartment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Institution'),
        ),
    ]
