# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170901_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='hours_schedule',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.InstitutionDepartment'),
        ),
    ]
