# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170901_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshiptype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
