# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170901_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ('institution',)},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='name',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Institution'),
            preserve_default=False,
        ),
    ]
