# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_institution_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='institution',
        ),
        migrations.AddField(
            model_name='institution',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='initials',
            field=models.CharField(default='lncc', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='name',
            field=models.CharField(default='default', max_length=70),
            preserve_default=False,
        ),
    ]
