# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_scholarship_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='advisor',
            field=models.BooleanField(default=False),
        ),
    ]
