# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_member_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='citation_name',
            field=models.CharField(default='Oliveira, V. D.', max_length=100),
            preserve_default=False,
        ),
    ]
