# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='line_of_research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.LineOfResearch'),
            preserve_default=False,
        ),
    ]
