# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20170911_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='initials',
            field=models.CharField(max_length=15),
        ),
    ]
