# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20170914_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('name', 'scholarship')},
        ),
    ]
