# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='unit',
            field=models.CharField(choices=[('GB', 'GB'), ('TB', 'TB'), ('CO', 'Cores'), ('BP', 'bps')], default='CO', max_length=2),
        ),
    ]
