# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_auto_20170911_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='short_description',
            field=models.CharField(default='Nuvem Computacional', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='description',
            field=models.TextField(),
        ),
    ]
