# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0013_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('initials', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('abstract', models.TextField()),
                ('resume', models.TextField()),
                ('date', models.DateField()),
                ('link', models.CharField(blank=True, max_length=150)),
                ('authors', models.ManyToManyField(through='publication.AuthorsOrder', to='member.Member')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Conference')),
            ],
            options={
                'ordering': ('-date', 'title'),
            },
        ),
        migrations.AddField(
            model_name='authorsorder',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Publication'),
        ),
    ]
