# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('initial', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('date', 'title')},
        ),
        migrations.AddField(
            model_name='publication',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publication.Conference'),
            preserve_default=False,
        ),
    ]
