# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20170904_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
