# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20170904_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='initial',
            new_name='initials',
        ),
    ]
