# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_authorsorder_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsorder',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='pub_authors',
        ),
    ]
