# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20170905_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bibtex',
            field=models.TextField(blank=True),
        ),
    ]
