# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20170915_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
